-- Magma Ring (kodr-map-v1) - generated by Kodr
-- Drop into ServerScriptService. Builds the whole map at runtime.
local scale = 6
local MAP = [
  "LLLLSSSSSSLLLL",
  "LL..PPPPPP..LL",
  "L..PPPPPPPP..L",
  "L.PPPPPPPPPP.L",
  "L..PPPPPPPP..L",
  "LL..PPPPPP..LL",
  "LLLLPPPPPPLLLL",
  "LLLLPPPPPPLLLL",
  "LL..PPPPPP..LL",
  "L.PPPPPPPPPP.L",
  "L..PPPPPPPP..L",
  "L.PPPPPPPPPP.L",
  "LL..PPPPPP..LL",
  "LLLLSSSSSSLLLL"
]

local TILES = {
  ["#"] = {Material = Enum.Material.Brick,        Color = Color3.fromRGB(90, 90, 95)},
  ["T"] = {Material = Enum.Material.WoodPlanks,   Color = Color3.fromRGB(70, 45, 25)},
  ["R"] = {Material = Enum.Material.Rock,         Color = Color3.fromRGB(120, 122, 125)},
  ["W"] = {Material = Enum.Material.Water,        Color = Color3.fromRGB(30, 90, 160)},
  ["L"] = {Material = Enum.Material.CrackedLava,  Color = Color3.fromRGB(255, 60, 0)},
  ["D"] = {Material = Enum.Material.Metal,        Color = Color3.fromRGB(60, 60, 65)},
  ["C"] = {Material = Enum.Material.Gold,         Color = Color3.fromRGB(255, 200, 60)},
  ["P"] = {Material = Enum.Material.Rock,         Color = Color3.fromRGB(200, 60, 60)},
  ["S"] = {Material = Enum.Material.Sand,         Color = Color3.fromRGB(215, 190, 150)},
  ["B"] = {Material = Enum.Material.Wood,         Color = Color3.fromRGB(140, 110, 75)},
  ["H"] = {Material = Enum.Material.Slate,        Color = Color3.fromRGB(90, 40, 40)},
  ["G"] = {Material = Enum.Material.Metal,        Color = Color3.fromRGB(40, 200, 120)},
}

local folder = Instance.new("Folder", workspace)
folder.Name = "Magma Ring"
local origin = Vector3.new(-#MAP[1] * scale / 2, 0, -#MAP * scale / 2)

for z, row in ipairs(MAP) do
    for x = 1, #row do
        local tile = TILES[row:sub(x, x)]
        if not tile then continue end
        local part = Instance.new("Part")
        part.Anchored = true
        part.TopSurface = Enum.SurfaceType.Smooth
        part.BottomSurface = Enum.SurfaceType.Smooth
        part.Material = tile.Material
        part.Color = tile.Color
        part.Size = Vector3.new(scale, row:sub(x, x) == "L" and 2 or 8, scale)
        part.Position = origin + Vector3.new((x - 1) * scale, 0, (z - 1) * scale)
        part.Parent = folder
    end
end
