"""Compile any kodr-map-v1 JSON into native builders for any engine.

Usage:
    python compile_map.py mymap.json --engine roblox --out buildMap.lua
    python compile_map.py mymap.json --engine unity  --out MapBuilder.cs
    python compile_map.py mymap.json --engine godot  --out map_builder.gd
    python compile_map.py mymap.json --preview        # ascii render in terminal
"""
import argparse
import json
import textwrap


TILE = {
    ".": ("floor", None),
    "#": ("wall", "brick"),
    "T": ("tree", "wood"),
    "R": ("rock", "stone"),
    "W": ("water", "water"),
    "L": ("lava", "lava"),
    "D": ("door", "metal"),
    "C": ("chest", "gold"),
    "P": ("enemy_spawn", "rock"),
    "S": ("spawn", "sand"),
    "B": ("bridge", "wood"),
    "H": ("hazard", "obstacle"),
    "G": ("goal", "metal"),
}


def _rows(m):
    return [list(r) for r in m.get("heightmap", [])]


def ascii_preview(m):
    legend = {".": " ", "#": chr(0x2588), "T": "T", "R": "R", "W": "~",
              "L": "~", "D": "D", "C": "$", "P": "E", "S": "S", "B": "=",
              "H": "!", "G": "G"}
    lines = []
    for row in _rows(m):
        lines.append("".join(legend.get(ch, "?") for ch in row))
    return "\n".join(lines)


def to_roblox_lua(m):
    heightmap = json.dumps(m.get("heightmap", []), indent=2).replace('"', '"')
    name = m.get("name", "KodrMap")
    scale = m.get("tile_scale", 4)
    return f'''-- {name} (kodr-map-v1) - generated by Kodr
-- Drop into ServerScriptService. Builds the whole map at runtime.
local scale = {scale}
local MAP = {heightmap}

local TILES = {{
  ["#"] = {{Material = Enum.Material.Brick,        Color = Color3.fromRGB(90, 90, 95)}},
  ["T"] = {{Material = Enum.Material.WoodPlanks,   Color = Color3.fromRGB(70, 45, 25)}},
  ["R"] = {{Material = Enum.Material.Rock,         Color = Color3.fromRGB(120, 122, 125)}},
  ["W"] = {{Material = Enum.Material.Water,        Color = Color3.fromRGB(30, 90, 160)}},
  ["L"] = {{Material = Enum.Material.CrackedLava,  Color = Color3.fromRGB(255, 60, 0)}},
  ["D"] = {{Material = Enum.Material.Metal,        Color = Color3.fromRGB(60, 60, 65)}},
  ["C"] = {{Material = Enum.Material.Gold,         Color = Color3.fromRGB(255, 200, 60)}},
  ["P"] = {{Material = Enum.Material.Rock,         Color = Color3.fromRGB(200, 60, 60)}},
  ["S"] = {{Material = Enum.Material.Sand,         Color = Color3.fromRGB(215, 190, 150)}},
  ["B"] = {{Material = Enum.Material.Wood,         Color = Color3.fromRGB(140, 110, 75)}},
  ["H"] = {{Material = Enum.Material.Slate,        Color = Color3.fromRGB(90, 40, 40)}},
  ["G"] = {{Material = Enum.Material.Metal,        Color = Color3.fromRGB(40, 200, 120)}},
}}

local folder = Instance.new("Folder", workspace)
folder.Name = "{name}"
local origin = Vector3.new(-#MAP[1] * scale / 2, 0, -#MAP * scale / 2)

for z, row in ipairs(MAP) do
    for x = 1, #row do
        local tile = TILES[row:sub(x, x)]
        if not tile then continue end
        local part = Instance.new("Part")
        part.Anchored = true
        part.TopSurface = Enum.SurfaceType.Smooth
        part.BottomSurface = Enum.SurfaceType.Smooth
        part.Material = tile.Material
        part.Color = tile.Color
        part.Size = Vector3.new(scale, row:sub(x, x) == "L" and 2 or 8, scale)
        part.Position = origin + Vector3.new((x - 1) * scale, 0, (z - 1) * scale)
        part.Parent = folder
    end
end
'''


def to_unity_csharp(m):
    name = m.get("name", "KodrMap")
    scale = m.get("tile_scale", 4)
    rows = json.dumps(m.get("heightmap", []))
    return textwrap.dedent(f'''\
    // {name} (kodr-map-v1) - generated by Kodr
    // Paste MapBuilder.cs into a Unity project, drop it on an empty GameObject,
    // parse the JSON into MapData (JsonUtility), and call MapBuilder.Build(...).
    using UnityEngine;

    public static class KodrMapBuilder
    {{
        [System.Serializable]
        public class MapData
        {{
            public string name = "{name}";
            public float tileScale = {scale};
            public string[] heightmap = {rows};
        }}

        public static GameObject Build(MapData map, Material ground, Material lava)
        {{
            GameObject root = new GameObject(map.name);
            float scale = map.tileScale;
            Vector3 origin = new Vector3(-map.heightmap[0].Length * scale / 2f, 0, -map.heightmap.Length * scale / 2f);

            for (int z = 0; z < map.heightmap.Length; z++)
            {{
                for (int x = 0; x < map.heightmap[z].Length; x++)
                {{
                    char c = map.heightmap[z][x];
                    if (c == '.') continue;

                    GameObject cube = GameObject.CreatePrimitive(PrimitiveType.Cube);
                    cube.name = c + "_" + x + "_" + z;
                    cube.transform.SetParent(root.transform);
                    cube.transform.position = origin + new Vector3(x * scale, 0, z * scale);
                    cube.transform.localScale = new Vector3(scale, c == 'L' ? 2f : 8f, scale);
                    cube.GetComponent<Collider>().isTrigger = (c == 'W' || c == 'L');
                    cube.GetComponent<Renderer>().sharedMaterial = (c == 'L' && lava) ? lava : ground;
                }}
            }}
            return root;
        }}
    }}
    ''')


def to_godot_gdscript(m):
    name = m.get("name", "KodrMap")
    scale = m.get("tile_scale", 4)
    rows = json.dumps(m.get("heightmap", []))
    return textwrap.dedent(f'''\
    # {name} (kodr-map-v1) - generated by Kodr
    # Attach to a Node3D. Builds the whole map as a static grid.
    extends Node3D

    const TILE_SCALE := {scale}

    const COLORS := {{
        "#": Color(0.35, 0.35, 0.37),
        "T": Color(0.42, 0.32, 0.18),
        "R": Color(0.47, 0.47, 0.49),
        "W": Color(0.12, 0.35, 0.63),
        "L": Color(0.95, 0.28, 0.05),
        "D": Color(0.30, 0.30, 0.33),
        "C": Color(0.90, 0.72, 0.25),
        "P": Color(0.78, 0.24, 0.24),
        "S": Color(0.85, 0.74, 0.58),
        "B": Color(0.55, 0.43, 0.29),
        "H": Color(0.60, 0.30, 0.20),
        "G": Color(0.20, 0.75, 0.40)
    }}

    const HEIGHTMAP := {rows}

    func _ready() -> void:
        var origin := Vector3(-HEIGHTMAP[0].length() * TILE_SCALE / 2.0, 0, -HEIGHTMAP.size() * TILE_SCALE / 2.0)
        for z in HEIGHTMAP.size():
            for x in HEIGHTMAP[z].length():
                var code := HEIGHTMAP[z][x]
                if code == ".":
                    continue
                var box := BoxMesh.new()
                box.size = Vector3(TILE_SCALE, 8.0 if code != "L" else 2.0, TILE_SCALE)
                var mat := StandardMaterial3D.new()
                mat.albedo_color = COLORS.get(code, Color.GRAY)
                box.material = mat

                var mesh := MeshInstance3D.new()
                mesh.mesh = box
                mesh.position = origin + Vector3(x * TILE_SCALE, 0, z * TILE_SCALE)
                add_child(mesh)

                if code != "W" and code != "L":
                    var body := StaticBody3D.new()
                    var col := CollisionShape3D.new()
                    var shape := BoxShape3D.new()
                    shape.size = Vector3(TILE_SCALE, 8.0, TILE_SCALE)
                    col.shape = shape
                    body.add_child(col)
                    body.position = mesh.position
                    add_child(body)
    ''')


BUILDERS = {"roblox": to_roblox_lua, "unity": to_unity_csharp, "godot": to_godot_gdscript}


def main():
    p = argparse.ArgumentParser(description="Compile kodr-map-v1 JSON into engine builders")
    p.add_argument("mapfile")
    p.add_argument("--engine", choices=BUILDERS.keys())
    p.add_argument("--out")
    p.add_argument("--preview", action="store_true")
    args = p.parse_args()

    with open(args.mapfile, "r", encoding="utf-8") as f:
        m = json.load(f)

    if args.preview:
        print(ascii_preview(m))
        return

    code = BUILDERS[args.engine](m)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(code)
        print(f"wrote {args.out}")
    else:
        print(code)


if __name__ == "__main__":
    main()