// Magma Ring (kodr-map-v1) - generated by Kodr
// Paste MapBuilder.cs into a Unity project, drop it on an empty GameObject,
// parse the JSON into MapData (JsonUtility), and call MapBuilder.Build(...).
using UnityEngine;

public static class KodrMapBuilder
{
    [System.Serializable]
    public class MapData
    {
        public string name = "Magma Ring";
        public float tileScale = 6;
        public string[] heightmap = ["LLLLSSSSSSLLLL", "LL..PPPPPP..LL", "L..PPPPPPPP..L", "L.PPPPPPPPPP.L", "L..PPPPPPPP..L", "LL..PPPPPP..LL", "LLLLPPPPPPLLLL", "LLLLPPPPPPLLLL", "LL..PPPPPP..LL", "L.PPPPPPPPPP.L", "L..PPPPPPPP..L", "L.PPPPPPPPPP.L", "LL..PPPPPP..LL", "LLLLSSSSSSLLLL"];
    }

    public static GameObject Build(MapData map, Material ground, Material lava)
    {
        GameObject root = new GameObject(map.name);
        float scale = map.tileScale;
        Vector3 origin = new Vector3(-map.heightmap[0].Length * scale / 2f, 0, -map.heightmap.Length * scale / 2f);

        for (int z = 0; z < map.heightmap.Length; z++)
        {
            for (int x = 0; x < map.heightmap[z].Length; x++)
            {
                char c = map.heightmap[z][x];
                if (c == '.') continue;

                GameObject cube = GameObject.CreatePrimitive(PrimitiveType.Cube);
                cube.name = c + "_" + x + "_" + z;
                cube.transform.SetParent(root.transform);
                cube.transform.position = origin + new Vector3(x * scale, 0, z * scale);
                cube.transform.localScale = new Vector3(scale, c == 'L' ? 2f : 8f, scale);
                cube.GetComponent<Collider>().isTrigger = (c == 'W' || c == 'L');
                cube.GetComponent<Renderer>().sharedMaterial = (c == 'L' && lava) ? lava : ground;
            }
        }
        return root;
    }
}
