# Magma Ring (kodr-map-v1) - generated by Kodr
# Attach to a Node3D. Builds the whole map as a static grid.
extends Node3D

const TILE_SCALE := 6

const COLORS := {
    "#": Color(0.35, 0.35, 0.37),
    "T": Color(0.42, 0.32, 0.18),
    "R": Color(0.47, 0.47, 0.49),
    "W": Color(0.12, 0.35, 0.63),
    "L": Color(0.95, 0.28, 0.05),
    "D": Color(0.30, 0.30, 0.33),
    "C": Color(0.90, 0.72, 0.25),
    "P": Color(0.78, 0.24, 0.24),
    "S": Color(0.85, 0.74, 0.58),
    "B": Color(0.55, 0.43, 0.29),
    "H": Color(0.60, 0.30, 0.20),
    "G": Color(0.20, 0.75, 0.40)
}

const HEIGHTMAP := ["LLLLSSSSSSLLLL", "LL..PPPPPP..LL", "L..PPPPPPPP..L", "L.PPPPPPPPPP.L", "L..PPPPPPPP..L", "LL..PPPPPP..LL", "LLLLPPPPPPLLLL", "LLLLPPPPPPLLLL", "LL..PPPPPP..LL", "L.PPPPPPPPPP.L", "L..PPPPPPPP..L", "L.PPPPPPPPPP.L", "LL..PPPPPP..LL", "LLLLSSSSSSLLLL"]

func _ready() -> void:
    var origin := Vector3(-HEIGHTMAP[0].length() * TILE_SCALE / 2.0, 0, -HEIGHTMAP.size() * TILE_SCALE / 2.0)
    for z in HEIGHTMAP.size():
        for x in HEIGHTMAP[z].length():
            var code := HEIGHTMAP[z][x]
            if code == ".":
                continue
            var box := BoxMesh.new()
            box.size = Vector3(TILE_SCALE, 8.0 if code != "L" else 2.0, TILE_SCALE)
            var mat := StandardMaterial3D.new()
            mat.albedo_color = COLORS.get(code, Color.GRAY)
            box.material = mat

            var mesh := MeshInstance3D.new()
            mesh.mesh = box
            mesh.position = origin + Vector3(x * TILE_SCALE, 0, z * TILE_SCALE)
            add_child(mesh)

            if code != "W" and code != "L":
                var body := StaticBody3D.new()
                var col := CollisionShape3D.new()
                var shape := BoxShape3D.new()
                shape.size = Vector3(TILE_SCALE, 8.0, TILE_SCALE)
                col.shape = shape
                body.add_child(col)
                body.position = mesh.position
                add_child(body)
