(() => {
  "use strict";

  const year = document.getElementById("year");
  if (year) year.textContent = new Date().getFullYear();

  /* ---------- theme ---------- */
  const root = document.documentElement;
  const savedTheme = localStorage.getItem("kodr-theme");
  root.dataset.theme = savedTheme || "light";
  const themeBtn = document.getElementById("theme-toggle");
  if (themeBtn) {
    themeBtn.addEventListener("click", () => {
      const next = root.dataset.theme === "dark" ? "light" : "dark";
      root.dataset.theme = next;
      localStorage.setItem("kodr-theme", next);
    });
  }

  /* ---------- hero terminal typing ---------- */
  const CODE = `-- Magma Ring — generated by Kodr
local ring = buildRing(map, tiles)
ring.animate(30, function(t) return 1 - t end)
spawn.enemies("fighter", 3, ring.edge)
-- wall-jumps + coyote-time handling:
local coyote = 0.12
if time - lastGround <= coyote then
  Jump(math.max(jump, 62))
end`;

  const lineEl = document.getElementById("type-line");
  if (lineEl) {
    setTimeout(() => {
      let i = 0;
      const step = () => {
        if (document.hidden) { setTimeout(step, 200); return; }
        lineEl.textContent = CODE.slice(0, i);
        i += 1;
        if (i <= CODE.length) setTimeout(step, 8);
      };
      step();
    }, 700);
  }

  /* ---------- engine tabs ---------- */
  const SNIPPETS = {
    lua: `-- Roblox · Luau · server-side hit validation
swingRemote.OnServerEvent:Connect(function(player)
  if os.clock() - cd[player] < 0.8 then return end
  cd[player] = os.clock()
  local hit = workspace:Raycast(origin, dir * 10, params)
  if hit then hit.Instance.Parent.Humanoid:TakeDamage(25) end
end)`,
    cs: `// Unity · C# · object pool, zero alloc
GameObject go = pool.Dequeue();
go.transform.SetPositionAndRotation(pos, rot);
go.SetActive(true);
if (go.TryGetComponent<Rigidbody>(out var rb)) rb.velocity = Vector3.zero;`,
    gd: `# Godot · GDScript · coyote-time jump
if Input.is_action_just_pressed("jump"):
    var in_coyote = now - last_grounded < 0.12
    if is_on_floor() or in_coyote:
        velocity.y = jump_velocity
move_and_slide()`,
    cpp: `// Unreal · C++ · damage broadcast
void UHealthComponent::TakeDamage(float Amount)
{
    const float Old = CurrentHealth;
    CurrentHealth = FMath::Clamp(CurrentHealth - Amount, 0.f, MaxHealth);
    OnHealthChanged.Broadcast(this, Old, CurrentHealth);
}`,
  };

  const tabs = document.querySelectorAll(".tab");
  const body = document.getElementById("tab-body");
  if (tabs.length && body) {
    body.textContent = SNIPPETS.lua;
    tabs.forEach((tab) => {
      tab.addEventListener("click", () => {
        tabs.forEach((t) => t.classList.remove("active"));
        tab.classList.add("active");
        body.textContent = SNIPPETS[tab.dataset.tab] || "";
      });
    });
  }

  /* ---------- scroll reveal ---------- */
  const hero = document.querySelector(".hero");
  if (hero) hero.classList.add("in");
  const targets = document.querySelectorAll(".section, .marquee");
  targets.forEach((el) => el.classList.add("reveal"));
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => { if (e.isIntersecting) { e.target.classList.add("in"); io.unobserve(e.target); } });
      },
      { threshold: 0.12 }
    );
    targets.forEach((el) => io.observe(el));
  } else {
    targets.forEach((el) => el.classList.add("in"));
  }

  /* ---------- mobile menu ---------- */
  const burger = document.querySelector(".nav-burger");
  const links = document.querySelector(".nav-links");
  if (burger && links) {
    burger.addEventListener("click", () => {
      links.classList.toggle("open");
    });
    links.querySelectorAll("a").forEach((a) => a.addEventListener("click", () => links.classList.remove("open")));
  }
})();