"""Kodr codegen: LLM-first game code with a guaranteed local template fallback."""
from __future__ import annotations

import os
from datetime import datetime, timezone

from . import llm, theme

CONCEPT_TEMPLATE = """You are Kodr, a game-generation engine. Produce ONLY a playable, self-contained game from the spec below.

Return strictly valid JSON with exactly this shape:
{{
  "title": "<short name>",
  "premise": "<one sentence>",
  "controls": "<string>",
  "win_condition": "<string>",
  "code_language": "<python>",
  "code": "<full python source>"
}}

RULES:
- The "code" string must have every newline escaped as \\n and every double
  quote inside the source escaped as \\". Never put ``` fences inside it.
- No text, explanation, or markdown outside the JSON object.

The code must be a single standalone Python file that runs with no third-party
imports other than stdlib (random, time allowed). A text-based game loop that
works in a plain terminal is perfectly acceptable and preferred.

INPUT: theme={theme_key!r} palette={palette!r} mechanics={mechanics!r}
PLAYER GOAL / BRIEF: {description}
"""

FALLBACK_CODE = '''# {title}
# Generated by Kodr (local fallback engine)
# Theme: {key}
"""A small playable text-and-number adventure. No external dependencies."""

import random

WORLD_ITEMS = ["sword", "shield", "coin", "potion", "map", "torch"]
ENEMIES = ["goblin", "slime", "skeleton", "bat"]
THEME_FLAVOR = "{key}"


class Game:
    def __init__(self, player_name="hero"):
        self.player = {"name": player_name, "hp": 100, "gold": 0,
                       "inventory": [], "rooms": 0}
        self.exit_open = False

    def room(self):
        self.player["rooms"] += 1
        item = random.choice(WORLD_ITEMS)
        print("You enter a chamber deep in the " + THEME_FLAVOR + " realm.")
        print("You find a " + item + ".")
        self.player["inventory"].append(item)

    def fight(self):
        foe = random.choice(ENEMIES)
        hr = 60 + random.randint(0, 40)
        print("A wild " + foe + " appears (HP " + str(hr) + ")!")
        while hr > 0 and self.player["hp"] > 0:
            action = input("[a]ttack / [d]efend / [run] > ").strip().lower()
            if action.startswith("a"):
                dmg = random.randint(8, 20)
                hr -= dmg
                print("You hit the " + foe + " for " + str(dmg) + ".")
            elif action.startswith("d"):
                self.player["hp"] += 5
                print("You brace and recover 5 HP.")
            else:
                print("You flee to safety.")
                return False
            if hr > 0:
                fd = random.randint(6, 18)
                self.player["hp"] -= fd
                print("The " + foe + " hits you for " + str(fd) +
                      " (you: " + str(self.player["hp"]) + ").")
        if self.player["hp"] <= 0:
            print("You have fallen.")
            return True
        loot = random.randint(10, 40)
        self.player["gold"] += loot
        print("You defeated the " + foe + " and earned " + str(loot) + " gold.")
        return False

    def explore(self, n=12):
        while n > 0 and self.player["hp"] > 0:
            self.room()
            if random.random() < 0.5:
                if self.fight():
                    return
            n -= 1
        self.exit_open = True
        print("You find the old exit and seal your legend in the " +
              THEME_FLAVOR + " halls.")

    def play(self):
        print("=== " + self.player["name"] + ", welcome to Kodr (" +
              THEME_FLAVOR + ") ===")
        print("Commands: 'room', 'fight', 'explore', 'stats', 'quit'")
        while self.player["hp"] > 0:
            cmd = input("> ").strip().lower()
            if cmd.startswith("q"):
                break
            elif cmd == "room":
                self.room()
            elif cmd == "fight":
                self.fight()
            elif cmd == "explore":
                self.explore()
            elif cmd == "stats":
                print(self.player)
            else:
                print("Unknown command '" + cmd + "'.")


if __name__ == "__main__":
    Game(input("Your name > ")).play()
'''

# Note: braces in the template above are literal in outputs we do *not* format.
# We assemble FALLBACK_CODE via .replace() so no str.format() conflicts.


def _fallback(title, key, description):
    code = FALLBACK_CODE.replace("{title}", title).replace("{key}", key)
    if "{description}" in code:
        code = code.replace("{description}", (description or "").replace("}", "}}"))
    return code


def _llm_messages(key, pal, mechanics, description):
    return [
        {"role": "system", "content": CONCEPT_TEMPLATE.format(
            theme_key=key, palette=list(pal), mechanics=mechanics,
            description=description)},
        {"role": "user", "content": "Build it."},
    ]


def _validate(code):
    if not code or len(code) < 60:
        return False
    return ("def " in code or "import " in code) and ("print" in code or "class " in code)


def generate(description="", theme_key=None, palette=None, mechanics=None):
    """Return {'code', 'engine', 'title', 'error', 'meta'}."""
    key = theme_key or theme.detect_theme(description)
    pal = palette or theme.PALETTES[key]["colors"][:4]
    mech = mechanics or theme.detect_mechanics(description)
    meta = {"theme": key, "palette": pal, "mechanics": mech, "description": description}

    msgs = _llm_messages(key, pal, mech, description)

    best_raw = None
    parsed = None
    for attempt in range(2):
        raw = llm.chat(llm.CODER_MODEL, msgs, max_tokens=2600, temperature=0.35)
        if raw is None:
            break  # router unreachable / no token — do not retry
        best_raw = raw
        parsed = llm.parse_json(raw)
        if parsed and parsed.get("code"):
            break
        msgs = msgs + [{"role": "assistant", "content": raw},
                       {"role": "user", "content": "That was not valid JSON. Return ONLY a single valid JSON object, with all newlines in the code string escaped as \\n."}]

    if parsed and parsed.get("code") and _validate(parsed["code"]):
        return {
            "code": parsed["code"],
            "engine": "router:Qwen2.5-Coder-7B",
            "title": parsed.get("title") or _title(description),
            "meta": meta,
            "error": None,
        }

    title = _title(description)
    return {
        "code": _fallback(title, key, description),
        "engine": "local-template (LLM unavailable this run)",
        "title": title,
        "meta": meta,
        "error": None,
    }


def _title(description):
    words = (description or "").split()[:4]
    return (" ".join(w.capitalize() for w in words) if words else "Kodr Adventure")


def concept_to_py(concept):
    key = concept.get("theme", "volcanic")
    code = concept.get("code") or _fallback("Kodr Gen", key, concept.get("description", ""))
    header = (
        "# Kodr-generated game\n"
        "# engine: %s | theme: %s | %s\n"
        "# concept: %r\n"
        "\n" % (
            concept.get("engine", "?"),
            key,
            datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            {k: v for k, v in concept.items() if k != "code"},
        )
    )
    return header + "\n" + code