"""Kodr 3D: builds real, downloadable meshes (OBJ + GLB + STL) from any world,
plus a best-effort cloud upgrade via a public TripoSR Space."""
from __future__ import annotations

import json
import math
import os
import struct
import tempfile
import threading

from PIL import Image, ImageDraw

from . import theme as theme_mod

TILE_HEIGHT = {
    ".": 0, "#": 1.0, "R": 0.9, "T": 1.5, "W": 0.45, "L": 0.30,
    "P": 0.15, "S": 0.12, "B": 0.55, "G": 1.25, "C": 0.55, "D": 1.5, "H": 0.4,
}


def _char_color(ch, key, pal):
    if ch == "L":
        return (255, 96, 28)
    if ch == "W":
        return (36, 96, 168)
    colors = pal["colors"]
    idx = (hash(ch + key) % 997) % len(colors)
    return colors[idx]


def synthesize_grid(pal, key, size=20):
    """Produce a heightmap grid (list[str]) for a theme palette."""
    tiles = theme_mod.tile_class_for_theme(key)
    rng = 20
    rows = []
    for z in range(size):
        row = []
        for x in range(size):
            edge = min(x, z, size - 1 - x, size - 1 - z)
            if key == "volcanic" and edge <= 2:
                row.append("L")
                continue
            if key == "neon" and edge <= 1:
                row.append("H")
                continue
            pick = tiles[(hash((x, z)) % (rng * 3)) * 7 // 21 % len(tiles)] if False else tiles[(x * 7 + z * 13 + hash(key)) % len(tiles)]
            row.append(pick)
        rows.append("".join(row))
    return rows


def _cube(px, py, pz, s, color):
    """Return (positions[8], triangles[12]) for a cube centred at (px,py,pz)."""
    h = s / 2.0
    x0, x1 = px - h, px + h
    y0, y1 = py, py + s
    z0, z1 = pz - h, pz + h
    v = [
        (x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1),  # bottom
        (x0, y1, z0), (x1, y1, z0), (x1, y1, z1), (x0, y1, z1),  # top
    ]
    quads = [(0, 1, 2, 3), (4, 5, 6, 7), (0, 1, 5, 4), (2, 3, 7, 6), (1, 2, 6, 5), (0, 3, 7, 4)]
    tris = []
    for q in quads:
        tris.append((v[q[0]], v[q[1]], v[q[2]], color))
        tris.append((v[q[0]], v[q[2]], v[q[3]], color))
    return v, tris


def build_world(grid, pal, key, scale=1.0):
    """grid: list[str]. Returns dict with vertices, faces, colors and bounds."""
    verts, tris = [], []
    n = len(grid)
    for z, row in enumerate(grid):
        for x, ch in enumerate(row):
            if ch == "." or ch not in TILE_HEIGHT:
                continue
            h = TILE_HEIGHT.get(ch, 0.6)
            if ch == "T":
                _, t = _cube(x * scale, h * scale, z * scale, 0.85 * scale, (82, 60, 40))
                tris.extend(t)
                _, t = _cube(x * scale, h * scale + 0.85 * scale, z * scale, 0.9 * scale, _char_color("T", key, pal))
                tris.extend(t)
                continue
            color = _char_color(ch, key, pal)
            _, t = _cube(x * scale, h * scale, z * scale, scale, color)
            tris.extend(t)
    # deduplicate vertices by rounded position
    vmap, vlist = {}, []
    new_tris = []
    for tri in tris:
        idxs = []
        for vert in tri[:3]:
            pos = vert
            color = tri[3]
            keyp = (round(pos[0], 4), round(pos[1], 4), round(pos[2], 4))
            if keyp not in vmap:
                vmap[keyp] = len(vlist)
                vlist.append((pos, color))
            idxs.append(vmap[keyp])
        new_tris.append(tuple(idxs))
    return {"verts": vlist, "tris": new_tris, "size": n * scale}


def write_obj(world, root):
    colors = {}
    lines = ["# Kodr procedural world", "mtllib kodr_world.mtl"]
    for i, (pos, color) in enumerate(world["verts"]):
        lines.append("v %.3f %.3f %.3f" % (pos[0], pos[2], pos[1]))
        ckey = tuple(color)
        if ckey not in colors:
            colors[ckey] = "mat%03d" % len(colors)
    # material assign per triangle
    mtl_lines = []
    for ckey, name in colors.items():
        r, g, b = [v / 255.0 for v in ckey]
        mtl_lines.append("newmtl %s" % name)
        mtl_lines.append("Kd %.3f %.3f %.3f" % (r, g, b))
    for tri in world["tris"]:
        c = world["verts"][tri[0]][1]
        lines.append("usemtl %s" % colors[tuple(c)])
        lines.append("f %d %d %d" % (tri[0] + 1, tri[1] + 1, tri[2] + 1))
    with open(os.path.join(root, "kodr_world.obj"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    with open(os.path.join(root, "kodr_world.mtl"), "w", encoding="utf-8") as f:
        f.write("\n".join(mtl_lines))
    return "kodr_world.obj"


def write_stl(world, root):
    tris = world["tris"]
    with open(os.path.join(root, "kodr_world.stl"), "wb") as f:
        f.write(b"Kodr - generated by Kodr game engine" + b"\x00" * 44)
        f.write(struct.pack("<I", len(tris)))
        for idx in tris:
            a = world["verts"][idx[0]][0]
            b = world["verts"][idx[1]][0]
            c = world["verts"][idx[2]][0]
            ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
            vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
            nx, ny, nz = uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx
            ln = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
            f.write(struct.pack("<3f", nx / ln, ny / ln, nz / ln))
            for p in (a, b, c):
                f.write(struct.pack("<3f", p[0], p[2], p[1]))
            f.write(struct.pack("<H", 0))
    return "kodr_world.stl"


def write_glb(world, root):
    pos, norm, col, idx = [], [], [], []
    for vertex in world["verts"]:
        vec, color = vertex
        pos += list(vec)
        col += [c / 255.0 for c in color] + [1.0]
    for tri in world["tris"]:
        a, b, c = tri
        va, vb, vc = world["verts"][a][0], world["verts"][b][0], world["verts"][c][0]
        ux, uy, uz = vb[0] - va[0], vb[1] - va[1], vb[2] - va[2]
        vx, vy, vz = vc[0] - va[0], vc[1] - va[1], vc[2] - va[2]
        nx, ny, nz = uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx
        ln = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
        for i in (a, b, c):
            norm += [nx / ln, ny / ln, nz / ln]
            idx.append(i)
    nv = len(world["verts"])
    # assemble binary
    fmt_pos = struct.Struct("<%df" % (len(pos)))
    fmt_col = struct.Struct("<%df" % (len(col)))
    fmt_norm = struct.Struct("<%df" % (len(norm)))
    index_bytes = struct.pack("<%dH" % len(idx), *idx) if nv <= 65535 else struct.pack("<%dI" % len(idx), *idx)
    comp_type = 5123 if nv <= 65535 else 5125
    bin_pos = fmt_pos.pack(*pos)
    bin_norm = fmt_norm.pack(*norm)
    bin_col = fmt_col.pack(*col)
    bin = bin_pos + bin_norm + bin_col + index_bytes
    off_pos = 0
    off_norm = off_pos + len(bin_pos)
    off_col = off_norm + len(bin_norm)
    off_idx = off_col + len(bin_col)
    byte_len = len(bin)
    gltf = {
        "asset": {"version": "2.0", "generator": "Kodr"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "name": "KodrWorld"}],
        "meshes": [{"primitives": [{
            "attributes": {"POSITION": 1, "NORMAL": 2, "COLOR_0": 3},
            "indices": 4,
            "material": 0,
        }]}],
        "materials": [{"pbrMetallicRoughness": {"baseColorFactor": [1, 1, 1, 1], "metallicFactor": 0.0, "roughnessFactor": 0.9}, "name": "KodrPalette", "doubleSided": True}],
        "buffers": [{"byteLength": byte_len}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": off_pos, "byteLength": len(bin_pos), "target": 34962},
            {"buffer": 0, "byteOffset": off_norm, "byteLength": len(bin_norm), "target": 34962},
            {"buffer": 0, "byteOffset": off_col, "byteLength": len(bin_col), "target": 34962},
            {"buffer": 0, "byteOffset": off_idx, "byteLength": len(index_bytes), "target": 34963},
        ],
        "accessors": [
            {"bufferView": 0, "byteOffset": 0, "componentType": 5126, "count": nv, "type": "VEC3", "min": [0, 0, 0], "max": [1, 1, 1]},
            {"bufferView": 1, "byteOffset": 0, "componentType": 5126, "count": nv, "type": "VEC3"},
            {"bufferView": 2, "byteOffset": 0, "componentType": 5126, "count": nv, "type": "VEC4"},
            {"bufferView": 3, "byteOffset": 0, "componentType": comp_type, "count": len(idx), "type": "SCALAR"},
        ],
    }
    # fix bounds for accessor 0
    xs = [v[0] for v in [e[0] for e in world["verts"]]]
    ys = [v[1] for v in [e[0] for e in world["verts"]]]
    zs = [v[2] for v in [e[0] for e in world["verts"]]]
    gltf["accessors"][0]["min"] = [min(xs), min(ys), min(zs)]
    gltf["accessors"][0]["max"] = [max(xs), max(ys), max(zs)]
    json_bytes = json.dumps(gltf, separators=(",", ":")).encode("utf-8")
    # padding to 4 bytes
    while len(json_bytes) % 4 != 0:
        json_bytes += b" "
    while len(bin) % 4 != 0:
        bin += b"\x00"
    total = 12 + 8 + len(json_bytes) + 8 + len(bin)
    with open(os.path.join(root, "kodr_world.glb"), "wb") as f:
        f.write(struct.pack("<I", 0x46546C67))
        f.write(struct.pack("<I", 2))
        f.write(struct.pack("<I", total))
        f.write(struct.pack("<I", len(json_bytes)))
        f.write(struct.pack("<I", 0x4E4F534A))
        f.write(json_bytes)
        f.write(struct.pack("<I", len(bin)))
        f.write(struct.pack("<I", 0x004E4942))
        f.write(bin)
    return "kodr_world.glb"


def render_preview(world, out_path, size=(460, 340)):
    """Dimetric preview with painter's-algorithm shading -> PNG."""
    scale = None
    verts = world["verts"]
    nxs = min(v[0] for v, _ in verts)
    nx2 = max(v[0] for v, _ in verts)
    nzs = min(v[2] for v, _ in verts)
    nz2 = max(v[2] for v, _ in verts)
    ny2 = max(v[1] for v, _ in verts)
    w = nx2 - nxs or 1
    d = nz2 - nzs or 1
    proj = []
    cx, cy, cz = (nxs + nx2) / 2, (ny2) / 2, (nzs + nz2) / 2
    m = max(w, d) or 1
    sx = size[0] / (m * 2.2)
    sy = size[1] / (m * 2.2 + 2)
    for v in verts:
        vec = v[0]
        dx, dy, dz = vec[0] - cx, vec[1] - cz, vec[2] - cy
        px = dx - dz
        py = dy - 0.5 * dx - 0.5 * dz
        proj.append((px, py))
    img = Image.new("RGB", size, (250, 250, 250))
    dr = ImageDraw.Draw(img)
    tris = sorted(world["tris"], key=lambda t: max(-(proj[t0][0] + proj[t0][1]) for t0 in t))
    for tri in tris:
        pts = [(size[0] / 2 + proj[i][0] * sx, size[1] - size[1] * 0.5 + proj[i][1] * sy) for i in tri]
        color = world["verts"][tri[0]][1]
        # pseudo-lighting: higher faces render slightly brighter (painter's order gives depth)
        shade = 1.0 + 0.12 * (world["verts"][tri[0]][0][1] / max(world["verts"][tri[0]][0][1], 1e-6))
        dr.polygon([(p[0], p[1]) for p in pts], fill=tuple(min(255, int(c * min(shade, 1.3))) for c in color))
    img.save(out_path)
    return out_path


def build(pal, key, grid=None, size=20, scale=1.0, outdir=None):
    outdir = outdir or tempfile.mkdtemp(prefix="kodr3d_")
    grid = grid or synthesize_grid(pal, key, size)
    world = build_world(grid, pal, key, scale)
    obj = write_obj(world, outdir)
    stl = write_stl(world, outdir)
    glb = write_glb(world, outdir)
    png = render_preview(world, os.path.join(outdir, "preview.png"))
    meta = {
        "theme": key,
        "grid": grid,
        "tiles": len(grid) * len(grid[0]),
        "voxels": len(world["tris"]) // 12,
        "palette": pal["colors"][:4],
    }
    return {
        "theme": key,
        "obj": os.path.join(outdir, obj),
        "stl": os.path.join(outdir, stl),
        "glb": os.path.join(outdir, glb),
        "preview": png,
        "meta": meta,
        "dir": outdir,
        "cloud": False,
    }


def _cloud_triposr(image_path, outdir):
    """Best-effort: real AI mesh via the public TripoSR Space. Returns paths or raises."""
    from gradio_client import Client  # imported lazily so the local path never needs it

    c = Client("stabilityai/TripoSR", verbose=False)
    maybe = c.predict(image_path, 64, api_name="/generate")
    paths = [p for p in maybe if isinstance(p, str) and os.path.exists(p)]
    if not paths:
        raise RuntimeError("TripoSR returned no mesh files")
    res = {}
    for p in paths:
        name = os.path.basename(p)
        ext = name.rsplit(".", 1)[-1]
        dst = os.path.join(outdir, "kodr_ai_" + name)
        import shutil
        shutil.copy(p, dst)
        res[ext] = dst
    return res


def generate(text="", image_path=None, size=20):
    """Public entry: theme + optional image -> local mesh; cloud attempted on image."""
    if image_path:
        try:
            from . import vision
            rep = vision.analyze_image(image_path)
            key = vision._theme_key(theme_mod.palette_for_image(rep.get("palette_rgb"), None)) if rep.get("ok") else theme_mod.detect_theme(text)
        except Exception:
            key = theme_mod.detect_theme(text)
    else:
        key = theme_mod.detect_theme(text)
    pal = theme_mod.PALETTES[key]
    outdir = tempfile.mkdtemp(prefix="kodr3d_")
    result = build(pal, key, size=min(size, 36), outdir=outdir)

    if image_path and os.environ.get("KODR_CLOUD_3D"):
        def run():
            try:
                result.update(_cloud_triposr(image_path, outdir))
                result["cloud"] = True
            except Exception as e:
                result["cloud"] = False
                result["cloud_error"] = str(e)[:120]
        th = threading.Thread(target=run, daemon=True)
        th.start()
        th.join(timeout=150)
    return result